# Header
menu:
  主页: /
  总览: /archives/index.html
  关于我们: /about/index.html
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: left
widgets:
- recent_posts
- tagcloud
- tag
- category
- archive
- links

# Links
links:
  作者博客: https://visn.online/

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins: 
fb_app_id:

# Duoshuo
duoshuo_shortname: reqianduan

# Baidu share
baidushare:  true